### ISSUE TITLE
LLVM Release error with Docker

### ISSUE THREAD

**Issue by tomizius** [google/fully-homomorphic-encryption#12]
Hey guys, first thank you for the code and the libary.

I just tried the docker installation guide on my arch linux system. I got the error which you describe in the troubleshooting area, but I got it with the docker image.

```
Step 6/6 : RUN bazel build ...
 ---> Running in 5529e63f0ab1
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Repository llvm_toolchain instantiated at:
  /usr/src/fhe/WORKSPACE:59:15: in <toplevel>
Repository rule llvm_toolchain defined at:
  /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
		_download_llvm_preconfigured(rctx)
	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
		fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz
Please ensure file name is correct.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
		_download_llvm_preconfigured(rctx)
	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
		fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz
Please ensure file name is correct.
ERROR: no such package '@llvm_toolchain//': Unknown LLVM release: clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz
Please ensure file name is correct.
INFO: Elapsed time: 12.690s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
The command '/bin/sh -c bazel build ...' returned a non-zero code: 
```

Is there any way to fix this?

Best regards

Thomas

**Comment by Cam2337** [comment]
> Error in fail: Unknown LLVM release: clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz

These log messages seem to indicate that the Docker image was built after the change: `llvm_version = "10.0.1"` was made to `WORKSPACE`. Could you please try reverting this change prior to following the steps to build the Docker image?

If this doesn't work, could you share any additional log messages produced when building the Docker image with the default `WORKSPACE` (e.g. with `llvm_version = "10.0.0"`)?

Thanks for reaching out!

**Comment by tomizius** [comment]
Ahh okay in this case it's my bad. Thank you for your help.
I didn't realized, that the Dockerfile uses the `WORKSPACE` file in the directory where I build the container.
Yes, first I tried to build it local and changed the version to 10.0.1 and when I changed it back to 10.0.0 it works. 

Thank you very much!

**Comment by Cam2337** [comment]
No worries! Glad things are working now! :)
